ejar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myejar.urls')),
    path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myejar/models.py
from decimal import Decimal
from django.db import models
from datetime import datetime
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.dispatch import receiver
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save


from django.forms import ValidationError

#customers
from django.db import models

class Customers(models.Model):
    kind = [
        ("فرد", "فرد"),
        ("مؤسسة", "مؤسسة"),
    ]
    id = models.BigAutoField(primary_key=True)
    ckind = models.CharField(max_length=50, choices=kind, verbose_name="نوع المستأجر")
    cID = models.BigIntegerField(verbose_name="رقم الاثبات" , blank=True, null=True)
    cDob = models.DateField(verbose_name="تاريخ الميلاد", blank=True,null=True)
    cName = models.CharField(max_length=50, verbose_name="اسم المستأجر")
    cNumber = models.BigIntegerField(max_length=10, verbose_name="رقم المستأجر", blank=True,null=True)
    cIdImage = models.ImageField(upload_to='Idphotos/%y/%m/%d', blank=True, verbose_name="صورة الاثبات")

    def __str__(self):
        return self.cName

    class Meta:
        verbose_name = 'المستأجرين'




class Buildings (models.Model):
    kind = [
        ("سكني","سكني"),
        ("تجاري","تجاري"),
        ("سكني وتجاري","سكني وتجاري"),
    ]
    bKind = models.CharField(max_length=50, choices=kind, verbose_name="نوع المبنى")
    dName = models.CharField(max_length=50, verbose_name=" اسم العقار في الصك ", blank=True)
    dID = models.CharField(primary_key=True, max_length= 20, verbose_name="رقم الصك ")
    dDate = models.DateField(verbose_name="تاريخ الصك",blank=True,null=True)
    bName = models.CharField(max_length=50, verbose_name=" اسم المبنى ")
    bAddress = models.CharField(max_length=50,  blank=True,verbose_name="عنوان المبنى" )
    bNote = models.TextField(max_length=500, blank=True,verbose_name="ملاحظة ")
    dImage = models.FileField(upload_to= 'Idphotos/%y/%m/%d',  blank=True,verbose_name="صورة الصك ")
    bimage = models.FileField(upload_to= 'Idphotos/%y/%m/%d',  blank=True,verbose_name="صورة المبنى ")

    def __str__(self):
        return self.bName
    class Meta:
        verbose_name = 'المباني'



class Units (models.Model):
    kind = [
        ("تجاري","تجاري"),
        ("سكني","سكني"),
        ("سكني وتجاري","سكني وتجاري"),
    ]
    kind2 = [
        ("شقة","شقة"),
        ("محل","محل"),
        ("دور ","دور "),
        ("عمارة ","عمارة "),
        ("فندق ","فندق "),
        ("أخرى ","أخرى "),
    ]
    id = models.BigAutoField(primary_key=True)
    building = models.ForeignKey(Buildings,on_delete= models.SET_DEFAULT, default= True, verbose_name="المبنى  ")
    uKind = models.CharField(max_length=50,  choices=kind, verbose_name="سكني ام تجاري",blank=True, null=True)
    uKind2 = models.CharField(max_length=50, choices=kind2, verbose_name="نوع الوحدة  ",blank=True, null=True)
    uName = models.CharField( max_length=50,verbose_name=" اسم الوحدة ")
    uNumber = models.BigIntegerField( verbose_name="رقم الوحدة - يجب ان يكون رقم خاص للوحدة ",blank=True, null=True)
    uRoomsNo = models.IntegerField(max_length=10,  verbose_name=" عدد الغرف ",blank=True, null=True)
    uFloor = models.IntegerField(max_length=10,blank=True, null=True, verbose_name="الدور  ")
    uElectricity = models.BigIntegerField(max_length=10, blank=True, null=True, verbose_name="رقم سداد الكهرباء  ")
    uWater = models.BigIntegerField(max_length=10,  verbose_name=" رقم سداد المياه ",blank=True, null=True)
    
    def __str__(self):
        return self.uName
    class Meta:
        verbose_name = 'الوحدات'







class Contracts(models.Model):
    kind = [
        ("تجاري","تجاري"),
        ("سكني","سكني"),
    ]
    statuspaymint = [
    ("تم السداد","تم السداد"),
    ("لم يتم السداد","لم يتم السداد"),
    ("الغي","الغي"),
    ]
    contract_kind = models.CharField(max_length=50,  choices=kind, verbose_name="سكني ام تجاري")
    contractNumber = models.BigIntegerField(max_length=50, verbose_name= "رقم العقد الالكتروني")
    customer = models.ForeignKey(Customers, on_delete= models.PROTECT, default= True, verbose_name="المستأجر")
    unit = models.ForeignKey(Units, on_delete= models.SET_DEFAULT, default= True, verbose_name="الوحدة")
    startDate = models.DateField(verbose_name="تاريخ البدء")
    endDate = models.DateField(verbose_name="تاريخ الانتهاء")
    payment_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True,verbose_name="القيمة الإيجارية لكامل العقد")
    cFile = models.FileField(upload_to= 'contract/%y/%m/%d',  blank=True,verbose_name="العقد  ")
    cNote = models.TextField(max_length=500, blank=True,verbose_name="ملاحظة ")
    
    @property
    def vat(self):
        if self.contract_kind == "تجاري":
            return self.payment_amount * Decimal('0.15')
        else:
            return 0

    @property
    def total_amount(self):
        return self.payment_amount + self.vat
    
    @property
    def duration_days(self):
        return (self.endDate - self.startDate).days
    
    def get_received_payments(self):
        return Payment_recived.objects.filter(payment__contract=self)
    
    
    
    def __str__(self):
        return f"{self.customer} - {self.unit}"
    

import uuid
class Payment(models.Model):
    payment_number = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    payment_due = models.DateField(null=True, blank=True)
    contract = models.ForeignKey(Contracts, on_delete=models.CASCADE, default=True)
    
    
    def __str__(self):
        return f"{self.contract.customer} - {self.amount} - {self.payment_due}"


class Payment_recived(models.Model):
    method = [
        ("حواله","حواله"),
        ("كاش","كاش"),
        ("شيك","شيك"),
        ("أخرى","أخرى"),
    ]
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE, default=True,related_name='payment_received')
    received_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    received_date = models.DateField(null=True, blank=True)
    payment_method = models.CharField(max_length=50,  choices=method, verbose_name="طريقة السداد  ",null=True, blank=True)
    doc_number = models.CharField(max_length=50, unique=True,verbose_name="بيانات المستند  " )
    
    @staticmethod
    def get_received_payments_for_contract(contract_id):
        contract = Contracts.objects.get(id=contract_id)
        return contract.get_received_payments()
    

    def __str__(self):
        return f"{self.payment.amount} - {self.received_amount} - {self.received_date} - {self.payment_method}"


    

    
class Login(models.Model):
    username = models.CharField(max_length=10)
    password = models.CharField(max_length=20)


class Expenses (models.Model):
    beneficiary = models.CharField(max_length=80 , verbose_name="اسم المستلم")
    bNumber = models.BigIntegerField(max_length= 10, verbose_name="رقم الجوال ")
    eamount = models.IntegerField(max_length= 10, verbose_name="المبلغ ")
    eamounttext = models.CharField(max_length= 100, verbose_name="المبلغ كتابة ", blank=True)
    info  = models.TextField(max_length=500, blank=True,verbose_name="مقابل ")
    eBuilding = models.ForeignKey(Buildings,on_delete= models.CASCADE,  verbose_name="المبنى  ")
    eDb = models.DateField(verbose_name="تاريخ الصرف")
    
    def __str__(self):
        return self.beneficiary
    class Meta:
        verbose_name = 'المصروفات'

units/models.py
from django.db import models

# Create your models here.

units/views.py
from django.shortcuts import render

# Create your views here.

templates/add_building.html
{% extends 'head.html' %}
{% load static %}
{% block content %}




<div class="content" id="content_clients" onload="updateClientsTable">
    <div class="title-info">
        <i class="fa fa-chart-bar"></i>
        <p id="numbers">بيانات المبنى</p>
    </div>

    <div class="formdiv" id="addCustomerForm" dir="rtl">
        <form method="POST" enctype="multipart/form-data" class="customer-form">
            {% csrf_token %}
              {{ form }}
            <div class="form-group">
                <button type="submit" class="save-button">حفظ</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/add_expenses.html
{% extends 'head.html' %}
{% load static %}
{% block content %}



<div class="content" id="content_clients" onload="updateClientsTable">
    <div class="title-info">
        <i class="fa fa-chart-bar"></i>
        <p id="numbers">بيانات المصروف </p>
    </div>

    <div class="formdiv" id="addCustomerForm" dir="rtl">
        <form method="POST" enctype="multipart/form-data" class="customer-form">
            {% csrf_token %}
              {{ form }}
            <div class="form-group">
                <button type="submit" class="save-button">حفظ</button>
            </div>
        </form>
    </div>
</div>
</div>
{% endblock content %}

templates/add_unit.html
{% extends 'head.html' %}
{% load static %}
{% block content %}




<div class="content" id="content_clients" onload="updateClientsTable">
    <div class="title-info">
        <i class="fa fa-chart-bar"></i>
        <p id="numbers">بيانات الوحدة</p>
    </div>

    <div class="formdiv" id="addCustomerForm" dir="rtl">
        <form method="POST" enctype="multipart/form-data" class="customer-form">
            {% csrf_token %}
              {{ form }}
            <div class="form-group">
                <button type="submit" class="save-button">حفظ</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/contract_create_or_update.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="content" id="content_clients” onload="updateClientsTable"> <div class="title-info"> <i class="fa fa-chart-bar"></i> <p id="numbers">بيانات العقد</p> </div>

<div class="formdiv">
<form dir="rtl" enctype="multipart/form-data" class="contarct" method="post" id="contract_form">
    {% csrf_token %}
    <!-- main form start --- in our case product form -->
    <div class="card" dir="rtl">
      
        <div class="card2">
            <h4 class="card-title"> إضافة عقد جديد</h4>
        </div>
    <div class="inputsss">
        <div id="label">
            <label for="{{ form.contract_kind.id_for_label }}"> نوع العقد:</label>
            {{ form.contract_kind }}
          </div>
          <div id="label">
            <label for="{{ form.contractNumber.id_for_label }}"> رقم العقد :</label>
            {{ form.contractNumber }}
          </div>
          <div id="label">
            <label for="{{ form.customer.id_for_label }}"> المستأجر:</label>
            {{ form.customer }}
          </div>
          <div id="label">
            <label for="{{ form.unit.id_for_label }}"> الوحدة:</label>
            {{ form.unit }}
          </div>
          <div id="label">
            <label for="{{ form.startDate.id_for_label }}"> تاريخ بداية العقد:</label>
            {{ form.startDate }}
          </div>
          <div id="label">
            <label for="{{ form.endDate.id_for_label }}"> تاريخ نهاية العقد:</label>
            {{ form.endDate }}
          </div>
          <div id="label">
            <label for="{{ form.payment_amount.id_for_label }}" > قيمة العقد بدون الضريبة:</label>
            {{ form.payment_amount }}
          </div>
          <div id="label">
            <label for="vat_amount">قيمة الضريبة (15%):</label>
            <input type="text" id="vat_amount" readonly>
        </div>
        
        <div id="label">
            <label for="total_amount">المبلغ الإجمالي (شامل الضريبة):</label>
            <input type="text" id="total_amount" readonly>
        </div>
        <div id="label">
          <label for="{{ form.endDate.id_for_label }}"> ملاحظات العقد  :</label>
          {{ form.cNote }}
        </div>
        <div id="label">
          <label for="{{ cFile.id_for_label }}">  عقد الايجار  :</label>
          {{ form.cFile }}
        </div>
        
 
    </div>
    </div>
    <!-- main form end --- in our case product form -->

        <div class="form-group" dir="rtl">
            <button type="submit" class="save-button">حفظ العقد</button>
        </div>
</form>


</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script>

$(document).ready(function() {
  // when user clicks add more btn of variants
  $('#add-payments-button').click(function(ev) {
    ev.preventDefault();
    var count = $('#item-payment').children().length;
    var tmplMarkup = $('#payments-template').html();
    var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
    $('#item-payment').append(compiledTmpl);

    // update form count
    $('#id_form-TOTAL_FORMS').attr('value', count + 1);
  });
});
</script>



<script>
    $(document).ready(function() {
      $('#contract_form').on('input', function() {
        var contractKind = $('#id_contract_kind').val();
        var paymentAmount = parseFloat($('#id_payment_amount').val());
        if (contractKind === 'تجاري' && !isNaN(paymentAmount)) {
          var vatAmount = paymentAmount * 0.15;
          var totalAmount = paymentAmount + vatAmount;
          $('#vat_amount').val(vatAmount.toFixed(2));
          $('#total_amount').val(totalAmount.toFixed(2));
        } else {
          $('#vat_amount').val('0.00');
          $('#total_amount').val(paymentAmount.toFixed(2));
        }
      });
    });
    
    </script>
{% endblock content %}

templates/contract_detail.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="content" id="content_contract">
    <div class="title-info">
        <i class="fa fa-chart-bar"></i>
        <p id="numbers"> بيانات العقد </p>
    </div>
</div>

<div dir="rtl" style="padding-right: 20px;">
    <p>رقم العقد: {{ contract.contractNumber }}</p>
    <br>
    <p> نوع العقد: {{ contract.contract_kind }}</p>
    <br>
    <p> المستأجر: {{ contract.customer }}</p>
    <br>
    <p> الوحدة: {{ contract.unit }}</p>
    <br>
    <p> تاريخ بداية العقد: {{ contract.startDate }}</p>
    <br>
    <p> تاريخ نهاية العقد: {{ contract.endDate }}</p>
    <br>
    <p> ملاحظات العقد  : {{ contract.cNote }}</p>
    <br>
    <p> قيمة الايجار: {{ contract.total_amount|floatformat:2 }}</p>
    <br>
    <p>المبلغ المتبقي: <span id="remainingAmount"></span></p>
    <br>
    {% if contract.cFile %}
    <a href="{{ contract.cFile.url }}" download>تحميل عقد الايجار</a>
{% else %}
    <p>لم يتم تحميل عقد</p>
{% endif %}
</div> 

<!-- Add more contract details here -->

<div class="content" id="content_contract">
    <div class="title-info">
        <i class="fa fa-chart-bar"></i>
        <p id="numbers"> الدفعات </p>
    </div>
    <div dir="rtl" style="padding-right: 20px;">
        <a dir="rtl" id="addBtn" class="action-button" href="{% url 'create_payment' contract.id %}">
            إضافة دفعة جديدة +
        </a>
    </div>
</div>

<table id="buildings-table" dir="rtl">
    <colgroup>
        <col span="1" style="width: 10%;" />
        <col span="1" style="width: 10%;" />
        <col span="1" style="width: 10%;" />
        <col span="1" style="width: 10%;" />

    </colgroup>
    <tr>
        <th style="color: #ffffff;"> قيمة الدفعة </th>
        <th style="color: #ffffff;"> تاريخ الاستحقاق </th>
        <th style="color: #ffffff;"> سداد  </th>
        <th style="color: #ffffff;"> حذف  </th>


    </tr>

    <tbody id="paymentTable">
        {% for payment in contract.payment_set.all %}
            <tr class="paymentsModule">
                <td>{{ payment.amount }}</td>
                <td>{{ payment.payment_due }}</td>
                <td style="background-color: rgba(87, 87, 87, 0.349);" ><a style="text-decoration: none; color: rgb(0, 71, 15);" href="{% url 'payment_received' payment.id %}"><i class="fa-solid fa-credit-card"></i> </a></td>
                <td style="background-color: rgba(255, 52, 52, 0.349);">
                    <a style="text-decoration: none; color: rgb(185, 3, 3);"
                        href="{% url 'delete_payment' payment.id %}">
                        <i class="fa-solid fa-trash"></i>
                    </a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="7">لا بوجد دفعات</td>
            </tr>
        {% endfor %}
        <div>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            </div>
        
    </tbody>
</table>

<div class="content" id="content_contract">
    <div class="title-info">
        <i class="fa fa-chart-bar"></i>
        <p id="numbers"> الدفعات المستلمة </p>
    </div>
</div>

<table id="buildings-table" dir="rtl">
    <colgroup>
      <col span="1" style="width: 10%;" />
      <col span="1" style="width: 10%;" />
      <col span="1" style="width: 10%;" />
      <col span="1" style="width: 10%;" />
      <col span="1" style="width: 10%;" />
    </colgroup>
    <tr>
      <th style="color: #ffffff;">الدفعة المستلمة</th>
      <th style="color: #ffffff;">تاريخ الاستلام</th>
      <th style="color: #ffffff;">طريقة الدفع</th>
      <th style="color: #ffffff;">طباعة </th>
      <th style="color: #ffffff;">حذف </th>
    </tr>
    <tbody id="previousPaymentTable">
        {% for payment in contract.payment_set.all %}
        {% for received_payment in payment.payment_received.all %}
        <tr class="previousPaymentsModule">
          <td>{{ received_payment.received_amount }}</td>
          <td>{{ received_payment.received_date }}</td>
          <td>{{ received_payment.payment_method }}</td>
          <td style="background-color: rgba(87, 87, 87, 0.349);"><a style="text-decoration: none; color: rgb(0, 71, 15);" href="{% url 'print_payment_received' received_payment.id %}" target="_blank"><i class="fa-solid fa-print"></i></a></td>
          <td style="background-color: rgba(255, 52, 52, 0.349);">
            <a style="text-decoration: none; color: rgb(185, 3, 3);"
                href="{% url 'delete_payment_received' received_payment.id %}">
                <i class="fa-solid fa-trash"></i>
            </a>
        </td>
    </td>
        </tr>
        {% endfor %}
        {% endfor %}
      </tbody>
  </table>



  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    // Calculate and display the remaining payment amount
    function calculateRemainingAmount() {
      var totalReceivedAmount = 0;
      $('.previousPaymentsModule').each(function() {
        var receivedAmount = parseFloat($(this).find('td:nth-child(1)').text());
        totalReceivedAmount += receivedAmount;
      });
      var contractAmount = parseFloat('{{ contract.total_amount }}');
      var remainingAmount = contractAmount - totalReceivedAmount;
      $('#remainingAmount').text(remainingAmount.toFixed(2));
    }

    // Call the calculateRemainingAmount function initially
    calculateRemainingAmount();

    // Call the calculateRemainingAmount function whenever a new received payment is added or removed
    $('#previousPaymentTable').on('DOMSubtreeModified', function() {
      calculateRemainingAmount();
    });
  });
</script>

{% endblock %}

templates/expenses.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="content" id="content_contract">
    <div class="title-info">
        <i class="fa fa-chart-bar"></i>
        <p id="numbers"> المصروفات  </p>
    </div>
</div>

<div dir="rtl" id="search_add">
    <a id="addBtn" class="action-button" href="{% url 'add_expenses' %}">
        إضافة مصروف جديد +
    </a>
</div>

<!-- Clients table -->
<table id="clients-table" dir="rtl">
    <colgroup>
        <col span="1" style="width: 10%;" />
        <col span="1" style="width: 10%;" />
        <col span="1" style="width: 10%;" />
        <col span="1" style="width: 10%;" />
        <col span="1" style="width: 20%;" />
        <col span="1" style="width: 5%;" />
        <col span="1" style="width: 5%;" />
    </colgroup>
    <tr>
        <th style="color: #ffffff;">اسم المستلم </th>
        <th style="color: #ffffff;">تاريخ الاستلام  </th>
        <th style="color: #ffffff;">المبلغ  </th>
        <th style="color: #ffffff;"> المبنى </th>
        <th style="color: #ffffff;">الخدمات </th>
        <th style="color: #ffffff;">طباعة</th>
        <th style="color: #ffffff;">حذف</th>
    </tr>
    <tbody id="customerTable">
        {% for expenses in expensesModule %}
        <tr class="customersModule">
            <td style="background-color:rgb(126, 189, 126);">{{ expenses.beneficiary }}</td>
            <td style="background-color:rgb(126, 189, 126);">{{ expenses.eDb }}</td>
            <td style="background-color:rgb(126, 189, 126);">{{ expenses.eamount }}</td>
            <td style="background-color:rgb(126, 189, 126);">{{ expenses.eBuilding }}</td>
            <td style="background-color:rgb(126, 189, 126);">{{ expenses.info }}</td>
            <td style="background-color: rgba(87, 87, 87, 0.349);"><a style="text-decoration: none; color: rgb(0, 71, 15);" href="{% url 'print_expenses' expenses.id %}" target="_blank"><i class="fa-solid fa-print"></i></a></td>
            <td style="background-color: rgba(255, 52, 52, 0.349);">
              <a style="text-decoration: none; color: rgb(185, 3, 3);"
                  href="{% url 'delete_expenses' expenses.id %}">
                  <i class="fa-solid fa-trash"></i>
              </a>
          </td>
        </tr>
        {% endfor %}
        
    </tbody>
    
</table>
</div>



{% endblock %}

templates/report.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="content" id="content_docs">
    <div class="title-info">
      <i class="fa fa-chart-bar"></i>
      <p id="numbers"> تقرير المستأجر:  {{ customer.cName }}   </p>
    </div>
    <div dir="rtl" style="padding-right: 20px;">
        <p>نوع المستأجر : {{ customer.ckind }}</p>
        <br>
        <p>رقم الإثبات : {{ customer.cID }}</p>
        <br>
        <p>تاريخ الميلاد : {{ customer.cDob }}</p>
        <br>
        <p>رقم الجوال : {{ customer.cNumber }}</p>
        <br>
        <p>صورة الهوية : {{ customer.cIdImage }}</p>
    </div>
  </div>


  <div class="content" id="content_docs">
    <div class="title-info">
      <i class="fa fa-chart-bar"></i>
      <p id="numbers"> عقود الإيجار    </p>
    </div>
    <div dir="rtl">
        <table id="contract-table" dir="rtl">
            <colgroup>
              <col span="1" style="width: 10%;" />
              <col span="1" style="width: 10%;" />
              <col span="1" style="width: 20%;" />
              <col span="1" style="width: 15%;" />
              <col span="1" style="width: 15%;" />
            </colgroup>
            <tr>
              <th style="color: #ffffff;">رقم العقد </th>
              <th style="color: #ffffff;">بداية العقد</th>
              <th style="color: #ffffff;">نهاية العقد</th>
              <th style="color: #ffffff;">الوحدة</th>
              <th style="color: #ffffff;">اجمالي الايجار</th>
            </tr>
            <tbody class="contractTable">
              {% for contract in contracts %}
                <tr class="contractsModule">
                  <td style="background-color:rgb(126, 189, 126);">{{ contract.contractNumber }}</td>
                  <td style="background-color:rgb(126, 189, 126);">{{ contract.startDate }}</td>
                  <td style="background-color:rgb(126, 189, 126);">{{ contract.endDate }}</td>
                  <td style="background-color:rgb(126, 189, 126);">{{ contract.unit }}</td>
                  <td style="background-color:rgb(126, 189, 126);">{{ contract.total_amount }}</td>
                </tr>

              {% endfor %}
            </tbody>
          </table>
  </div>
  </div>

  <div class="content" id="content_docs">
    <div class="title-info">
      <i class="fa fa-chart-bar"></i>
      <p id="numbers"> الدفعات </p>
    </div>
    <div dir="rtl">
        {% for contract in contracts %}
              <li>
                رقم العقد: {{ contract.contractNumber }}<br>
                الوحدة : {{ contract.unit.uName }}<br>
                <!-- Display other contract information -->
                
                <table id="buildings-table" dir="rtl">
                  <colgroup>
                    <col span="1" style="width: 10%;" />
                    <col span="1" style="width: 10%;" />
                  </colgroup>
                  <tr>
                    <th style="color: #ffffff;"> قيمة الدفعة</th>
                    <th style="color: #ffffff;">تاريخ الإستحقاق </th>
                  </tr>
                  <tbody id="PaymentTable">
                    {% for payment in contract.payment_set.all %}
                        <tr class="previousPaymentsModule">
                          <td>{{ payment.amount }}</td>
                          <td>{{ payment.payment_due }}</td>
                        </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </li>
              <hr>
            {% empty %}
              <li>No payments found.</li>
            {% endfor %}
  </div>
  </div>

  <div class="content" id="content_docs">
    <div class="title-info">
      <i class="fa fa-chart-bar"></i>
      <p id="numbers"> الدفعات المستلمة   </p>
    </div>
    <div dir="rtl">
        {% for contract in contracts %}
              <li>
                رقم العقد: {{ contract.contractNumber }}<br>
                الوحدة : {{ contract.unit.uName }}<br>
                <!-- Display other contract information -->
                
                <table id="buildings-table" dir="rtl">
                  <colgroup>
                    <col span="1" style="width: 10%;" />
                    <col span="1" style="width: 10%;" />
                    <col span="1" style="width: 10%;" />
                  </colgroup>
                  <tr>
                    <th style="color: #ffffff;">الدفعة المستلمة</th>
                    <th style="color: #ffffff;">تاريخ الاستلام</th>
                    <th style="color: #ffffff;">طريقة الدفع</th>
                  </tr>
                  <tbody id="previousPaymentTable">
                    {% for payment in contract.payment_set.all %}
                      {% for received_payment in payment.payment_received.all %}
                        <tr class="hrhrrh">
                          <td>{{ received_payment.received_amount }}</td>
                          <td>{{ received_payment.received_date }}</td>
                          <td>{{ received_payment.payment_method }}</td>
                        </tr>
                      {% endfor %}
                    {% endfor %}
                  </tbody>
                </table>
              </li>
              <hr>
            {% empty %}
              <li>No contracts found.</li>
            {% endfor %}
<br><br>

<h3 style="padding-right: 20px;">  اجمالي المبالغ المستلمة: {{ total_received_amount }} ريال</h3>

<h3 style="padding-right: 20px;">اجمالي المبالغ المتبقية  : {{ total_payment_amount }} ريال </h3>
  </div>





<!-- Display other customer information as needed -->



{% endblock content %}